# Generated by Django 4.2.13 on 2026-07-04 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
        ('tenants', '__first__'),
        ('inventory', '0001_initial'),
        ('reproduction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='insemination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to='reproduction.insemination'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='shed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.shed'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to='health.treatment'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'name')},
        ),
    ]
