# Generated by Django 4.2.13 on 2026-07-04 05:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('heifer', 'Heifer'), ('open', 'Open (Milking)'), ('inseminated', 'Inseminated'), ('pregnant', 'Pregnant'), ('dry', 'Dry'), ('sick', 'Sick'), ('sold', 'Sold'), ('dead', 'Dead'), ('culled', 'Culled')], default='heifer', max_length=20)),
                ('sire_tag', models.CharField(blank=True, max_length=50, verbose_name='Sire Tag / Bull ID')),
                ('lactation_number', models.PositiveSmallIntegerField(default=0)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.breed')),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calves', to='animals.animal', verbose_name='Dam (Mother)')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='tenants.animalgroup')),
                ('shed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='tenants.shed')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tag_number'],
                'unique_together': {('tenant', 'tag_number')},
            },
        ),
    ]
