# Generated by Django 4.2.13 on 2026-08-01 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="sire",
            field=models.ForeignKey(
                blank=True,
                help_text="Only set when the sire is itself a registered animal in this farm's records.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sired_calves",
                to="animals.animal",
                verbose_name="Sire (Father)",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="sire_tag",
            field=models.CharField(
                blank=True,
                help_text="Free-text identifier for an unregistered/outside sire (e.g. purchased AI semen) — used when `sire` isn't linked to a real record.",
                max_length=50,
                verbose_name="Sire Tag / Bull ID",
            ),
        ),
    ]
