# Generated by Django 4.2.13 on 2026-08-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_import", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("animals", "Animals"),
                    ("milk", "Milk Records"),
                    ("inseminations", "Inseminations"),
                ],
                max_length=20,
            ),
        ),
    ]
