# Generated by Django 4.2.13 on 2026-07-04 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group_vaccination', models.BooleanField(default=False)),
                ('vaccine_name', models.CharField(max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('dose', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_given', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.animal')),
                ('shed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='tenants.shed')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('diagnosis', models.CharField(max_length=300)),
                ('drug', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('injection', 'Injection'), ('topical', 'Topical'), ('iv', 'IV')], default='injection', max_length=20)),
                ('withdrawal_days', models.PositiveSmallIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('ongoing', 'Ongoing'), ('recovered', 'Recovered'), ('chronic', 'Chronic'), ('died', 'Died')], default='ongoing', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_given', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='animals.animal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('disease_name', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=10)),
                ('symptoms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_events', to='animals.animal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Deworming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group_deworming', models.BooleanField(default=False)),
                ('product', models.CharField(max_length=200)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dewormings', to='animals.animal')),
                ('shed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dewormings', to='tenants.shed')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dewormings', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
