# Generated by Django 4.2.13 on 2026-08-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("calving_due", "Calving Due"),
                    ("preg_check_due", "Pregnancy Check Due"),
                    ("dry_off_due", "Dry-off Due"),
                    ("close_up_due", "Close-up Period Starting"),
                    ("vaccination_due", "Vaccination Due"),
                    ("deworming_due", "Deworming Due"),
                    ("treatment_followup", "Treatment Follow-up Due"),
                    ("low_stock", "Low Stock Alert"),
                    ("milk_drop", "Milk Production Drop"),
                    ("system", "System Message"),
                ],
                max_length=30,
            ),
        ),
    ]
