# Generated by Django 4.2.13 on 2026-07-04 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('farm_name', models.CharField(blank=True, max_length=200)),
                ('herd_size', models.CharField(blank=True, choices=[('under-50', 'Under 50 animals'), ('50-200', '50 – 200 animals'), ('200-500', '200 – 500 animals'), ('500-plus', '500+ animals')], max_length=15)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
