# Generated by Django 4.2.13 on 2026-08-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(
                blank=True,
                help_text="Updated (throttled, at most once/minute) by UpdateLastActivityMiddleware on any authenticated request — used to compute 'currently online' for the platform admin dashboard.",
                null=True,
            ),
        ),
    ]
