# Generated by Django 4.2.13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetAssistForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('milk_yield', 'Milk Yield'), ('milk_revenue', 'Milk Revenue'), ('feed_cost', 'Feed Cost'), ('cash_position', 'Cash Position')], max_length=20)),
                ('scope', models.CharField(choices=[('animal', 'Animal'), ('shed', 'Shed'), ('group', 'Animal Group'), ('farm', 'Farm')], default='farm', max_length=10)),
                ('scope_id', models.CharField(blank=True, max_length=100)),
                ('horizon_days', models.PositiveSmallIntegerField(default=30)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetassist_forecasts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetassist_forecasts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VetAssistQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('sources', models.JSONField(blank=True, default=list, help_text='Modules consulted to build the answer')),
                ('used_external_research', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetassist_queries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetassist_queries', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VetAssistReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('animal', 'Animal'), ('shed', 'Shed'), ('group', 'Animal Group'), ('farm', 'Farm')], max_length=10)),
                ('entity_id', models.CharField(help_text='Animal tag number, shed ID, group ID, or blank for farm-wide', max_length=100)),
                ('include_research', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True)),
                ('used_external_research', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetassist_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetassist_reports', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
