# Generated by Django 4.2.13 on 2026-07-04 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insemination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insemination_type', models.CharField(choices=[('ai', 'Artificial Insemination'), ('bull', 'Natural Service (Bull)')], default='ai', max_length=10)),
                ('date', models.DateField()),
                ('semen_batch', models.CharField(blank=True, max_length=100)),
                ('bull_breed', models.CharField(blank=True, max_length=100)),
                ('bull_tag', models.CharField(blank=True, max_length=50)),
                ('repeat_number', models.PositiveSmallIntegerField(default=1, help_text='1=first service, 2=second repeat, etc.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inseminations', to='animals.animal')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inseminations_done', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inseminations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PregnancyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('rectal', 'Rectal Palpation'), ('ultrasound', 'Ultrasound'), ('blood', 'Blood Test'), ('milk', 'Milk Progesterone')], default='rectal', max_length=20)),
                ('result', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('repeat', 'Repeat (Recheck)')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_tests', to='animals.animal')),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preg_tests_done', to=settings.AUTH_USER_MODEL)),
                ('insemination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='reproduction.insemination')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_tests', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DryOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry_off_date', models.DateField()),
                ('expected_calving_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dry_offs', to='animals.animal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dry_offs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-dry_off_date'],
            },
        ),
        migrations.CreateModel(
            name='Calving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calving_date', models.DateField()),
                ('calving_type', models.CharField(choices=[('normal', 'Normal'), ('assisted', 'Assisted'), ('caesarean', 'Caesarean')], default='normal', max_length=15)),
                ('dam_condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('calf_tag', models.CharField(blank=True, max_length=50)),
                ('calf_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('stillborn', 'Stillborn')], default='female', max_length=10)),
                ('calf_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calvings', to='animals.animal')),
                ('insemination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calving', to='reproduction.insemination')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calvings', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-calving_date'],
            },
        ),
        migrations.CreateModel(
            name='Abortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gestation_stage_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cause', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abortions', to='animals.animal')),
                ('insemination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abortions', to='reproduction.insemination')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abortions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
