# Generated by Django 4.2.13 on 2026-08-01 04:31
# Hand-edited to add the bull -> natural data migration (see rename_bull_to_natural)
# — InseminationType.BULL's stored value changed from "bull" to "natural" when
# Embryo Transfer was added as a third type; existing rows must be updated or
# they'd be left holding a value that no longer matches any choice.

from django.db import migrations, models


def rename_bull_to_natural(apps, schema_editor):
    Insemination = apps.get_model("reproduction", "Insemination")
    Insemination.objects.filter(insemination_type="bull").update(insemination_type="natural")


def rename_natural_to_bull(apps, schema_editor):
    Insemination = apps.get_model("reproduction", "Insemination")
    Insemination.objects.filter(insemination_type="natural").update(insemination_type="bull")


class Migration(migrations.Migration):
    dependencies = [
        ("reproduction", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(rename_bull_to_natural, rename_natural_to_bull),
        migrations.AddField(
            model_name="insemination",
            name="donor_dam_breed",
            field=models.CharField(
                blank=True,
                help_text="Embryo transfer only — breed of the genetic dam (donor cow), distinct from the recipient animal",
                max_length=100,
                verbose_name="Donor Dam Breed",
            ),
        ),
        migrations.AddField(
            model_name="insemination",
            name="semen_source_company",
            field=models.CharField(
                blank=True,
                help_text="Company that collected/developed the semen or embryo",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="insemination",
            name="semen_supplier_company",
            field=models.CharField(
                blank=True,
                help_text="Company/distributor that supplied it to the farm (may differ from the source company)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="insemination",
            name="veterinary_practitioner_number",
            field=models.CharField(
                blank=True,
                help_text="License/registration number of the vet who performed the procedure, if performed by an external practitioner",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="insemination",
            name="bull_breed",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Bull/Sire Breed"
            ),
        ),
        migrations.AlterField(
            model_name="insemination",
            name="insemination_type",
            field=models.CharField(
                choices=[
                    ("natural", "Natural Service"),
                    ("ai", "Artificial Insemination"),
                    ("embryo", "Embryo Transfer"),
                ],
                default="ai",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="insemination",
            name="semen_batch",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Semen/Embryo Batch Number"
            ),
        ),
    ]
