# Generated by Django 4.2.13 on 2026-07-16 01:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('price_monthly_pkr', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for "contact sales" plans (e.g. Enterprise).', max_digits=10, null=True)),
                ('has_ai_assistant', models.BooleanField(default=False, help_text='VetAssist access')),
                ('has_priority_support', models.BooleanField(default=False, help_text='On-call + WhatsApp support')),
                ('has_custom_agents', models.BooleanField(default=False, help_text='Enterprise: custom agents trained on their content')),
                ('has_beta_access', models.BooleanField(default=False, help_text='Enterprise: early/beta feature access')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('payfast_plan_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether new subscribers can pick this plan')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='trialing', max_length=15)),
                ('gateway', models.CharField(choices=[('none', 'None (trial / not yet subscribed)'), ('stripe', 'Stripe'), ('payfast', 'PayFast'), ('manual', 'Manual / Invoiced')], default='none', max_length=10)),
                ('gateway_customer_id', models.CharField(blank=True, max_length=150)),
                ('gateway_subscription_id', models.CharField(blank=True, max_length=150)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('plan_amount_pkr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ai_usage_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void')], default='open', max_length=10)),
                ('gateway', models.CharField(choices=[('none', 'None (trial / not yet subscribed)'), ('stripe', 'Stripe'), ('payfast', 'PayFast'), ('manual', 'Manual / Invoiced')], default='manual', max_length=10)),
                ('gateway_invoice_id', models.CharField(blank=True, max_length=150)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('query', 'Query'), ('report', 'Report'), ('forecast', 'Forecast')], max_length=10)),
                ('model_name', models.CharField(max_length=50)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('api_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Actual Gemini API cost for this call', max_digits=10)),
                ('surcharge_percent', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5)),
                ('billed_amount_usd', models.DecimalField(decimal_places=6, default=0, help_text='api_cost_usd plus surcharge_percent — computed on save', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_records', to='subscriptions.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_records', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
