# Generated by Django 4.2.13 on 2026-07-04 05:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_heads', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MilkDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_type', models.CharField(choices=[('corporate', 'Corporate'), ('local', 'Local / Retail')], default='corporate', max_length=15)),
                ('date', models.DateField()),
                ('buyer_name', models.CharField(max_length=200)),
                ('gross_litres', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('lr_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Lactometer Reading', max_digits=5, null=True)),
                ('fat_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('snf_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('adjusted_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('price_per_litre', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_dispatches', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MilkConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('litres', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='milk.consumptionhead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_consumptions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('am', 'Morning (AM)'), ('pm', 'Evening (PM)')], max_length=5)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('snf_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='animals.animal')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_records_entered', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date', 'animal__tag_number'],
                'unique_together': {('tenant', 'animal', 'date', 'session')},
            },
        ),
    ]
