# Generated by Django 4.2.13 on 2026-08-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milkrecord",
            name="session",
            field=models.CharField(
                choices=[
                    ("am", "Morning (AM)"),
                    ("midday", "Midday"),
                    ("pm", "Evening (PM)"),
                ],
                max_length=10,
            ),
        ),
    ]
