# Generated by Django 4.2.13 on 2026-08-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tenant",
            name="province",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
